context("get_de_defaults")

test_that("The default arguments are spcified correctly",{
  x <- get_de_defaults()
  x_names <- sort(names(x))
  expected_names <- sort(c("deathThreshold", "er", "f", "mu_P", "mu_T", "offThreshold", "S_T"))
  expect_that(x, is_a("list"))
  expect_that(x[['er']], equals(10^(-4)))
  expect_that(x[['mu_T']], equals(0.02))
  expect_that(x[['mu_P']], equals(0.5))
  expect_that(x[['S_T']], equals(2 * 10^8))
  expect_that(x[['f']], equals(0.37))
  expect_that(x[['deathThreshold']], equals(0.01))
  expect_that(x[['offThreshold']], equals(0.1))
  expect_that(x_names, equals(expected_names))
})

test_that("Argument Specification Works",{
  x <- get_de_defaults(er = 5, mu_T = 6, mu_P = 7)
  x_names <- sort(names(x))
  expected_names <- sort(c("deathThreshold", "er", "f", "mu_P", "mu_T", "offThreshold", "S_T"))
  expect_that(x, is_a("list"))
  expect_that(x[['er']], equals(5))
  expect_that(x[['mu_T']], equals(6))
  expect_that(x[['mu_P']], equals(7))
  expect_that(x[['S_T']], equals(2 * 10^8))
  expect_that(x[['f']], equals(0.37))
  expect_that(x[['deathThreshold']], equals(0.01))
  expect_that(x[['offThreshold']], equals(0.1))
  expect_that(x_names, equals(expected_names))
})